# interface generated by SpecTcl version 1.1 from D:/class/s00/Classes/09/hello1.ui
#   root     is the parent window for this user interface

proc hello1_ui {root args} {

	# this treats "." as a special case

	if {$root == "."} {
	    set base ""
	} else {
	    set base $root
	}
    
	button $base.button#1 \
		-activeforeground blue \
		-background white \
		-command {.textbox insert end "Hello world"} \
		-foreground blue \
		-text Hello

	text $base.textbox \
		-background blue \
		-cursor X_cursor \
		-foreground white \
		-height 1 \
		-tabs 0 \
		-width 1


	# Geometry management

	grid $base.button#1 -in $root	-row 1 -column 1 
	grid $base.textbox -in $root	-row 2 -column 1  \
		-sticky nesw

	# Resize behavior management

	grid rowconfigure $root 1 -weight 0 -minsize 34
	grid rowconfigure $root 2 -weight 0 -minsize 138
	grid columnconfigure $root 1 -weight 0 -minsize 319
# additional interface code
# end additional interface code

}


# Allow interface to be run "stand-alone" for testing

catch {
    if [info exists embed_args] {
	# we are running in the plugin
	hello1_ui .
    } else {
	# we are running in stand-alone mode
	if {$argv0 == [info script]} {
	    wm title . "Testing hello1_ui"
	    hello1_ui .
	}
    }
}
