#//////////////////////////////////////////////////////////////////////////
#//
#//  This code is for instructional purposes only. It was generated for
#//  use in a graduate level course to show certain aspects of data
#//  storage algorithms. It has problems and should not be used 
#//  outside the class environment.
#//
#//  Author:  Thomas D. Citriniti     citrit@rpi.edu
#//  Class:   Advanced Computer Graphics and Data visualization
#//           Rensselaer Polytechnic Institute
#//  Date:    October 3, 1995
#//
#//////////////////////////////////////////////////////////////////////////


# CCFLAGS=-g -I/locker/44/000644/Mesa/@sys/include
CCFLAGS=-g -I/usr/lpp/xlC/include -I/locker/44/000644/Mesa/@sys/include  \
CXXFLAGS=-g -I/usr/lpp/xlC/include -I/locker/44/000644/Mesa/@sys/include  \
        -I/usr/include
#CCC=xlC
CCC=g++

CXXFLAGS = -g

LDFLAGS=-L/locker/44/000644/Mesa/@sys/lib -lglut -lMesaGLU \
        -lMesaGL -lXmu -lXt -lX11 -lm


objtest: objtest.o OGLRen.o 
	$(CCC) -g -o $@  $@.o OGLRen.o $(LDFLAGS)


clean:
	rm -f *~ core objtest *.o

tidy:
	rm -f core *~ *.o

# DO NOT DELETE THIS LINE -- make depend depends on it.
