/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jogl_JoglCanvas */

#ifndef _Included_jogl_JoglCanvas
#define _Included_jogl_JoglCanvas
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: LOCK */
#undef jogl_JoglCanvas_assert
#define jogl_JoglCanvas_assert 0L
/* Inaccessible static: isInc */
/* Inaccessible static: incRate */
#undef jogl_JoglCanvas_TOP_ALIGNMENT
#define jogl_JoglCanvas_TOP_ALIGNMENT 0.0f
#undef jogl_JoglCanvas_CENTER_ALIGNMENT
#define jogl_JoglCanvas_CENTER_ALIGNMENT 0.5f
#undef jogl_JoglCanvas_BOTTOM_ALIGNMENT
#define jogl_JoglCanvas_BOTTOM_ALIGNMENT 1.0f
#undef jogl_JoglCanvas_LEFT_ALIGNMENT
#define jogl_JoglCanvas_LEFT_ALIGNMENT 0.0f
#undef jogl_JoglCanvas_RIGHT_ALIGNMENT
#define jogl_JoglCanvas_RIGHT_ALIGNMENT 1.0f
#undef jogl_JoglCanvas_serialVersionUID
#define jogl_JoglCanvas_serialVersionUID -7644114512714619750LL
/* Inaccessible static: nameCounter */
#undef jogl_JoglCanvas_serialVersionUID
#define jogl_JoglCanvas_serialVersionUID -2284879212465893870LL
/* Inaccessible static: libLoaded */
/*
 * Class:     jogl_JoglCanvas
 * Method:    accum
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_accum
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    alphaFunc
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_alphaFunc
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    begin
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_begin
  (JNIEnv *, jobject, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    bindTexture
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_bindTexture
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    blendFunc
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_blendFunc
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    build1DMipmaps
 * Signature: (IIIIILjava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_jogl_JoglCanvas_build1DMipmaps
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     jogl_JoglCanvas
 * Method:    build2DMipmaps
 * Signature: (IIIIIILjava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_jogl_JoglCanvas_build2DMipmaps
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     jogl_JoglCanvas
 * Method:    callList
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_callList
  (JNIEnv *, jobject, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    canvasResized
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_canvasResized
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    clear
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_clear
  (JNIEnv *, jobject, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    clearAccum
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_clearAccum
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    clearColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_clearColor
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    clearDepth
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_clearDepth
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jogl_JoglCanvas
 * Method:    clearIndex
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_clearIndex
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    clearStencil
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_clearStencil
  (JNIEnv *, jobject, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    clipPlane
 * Signature: (IDDDD)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_clipPlane
  (JNIEnv *, jobject, jint, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     jogl_JoglCanvas
 * Method:    color3b
 * Signature: (BBB)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_color3b
  (JNIEnv *, jobject, jbyte, jbyte, jbyte);

/*
 * Class:     jogl_JoglCanvas
 * Method:    color3d
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_color3d
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     jogl_JoglCanvas
 * Method:    color3f
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_color3f
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    color3i
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_color3i
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    color3s
 * Signature: (SSS)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_color3s
  (JNIEnv *, jobject, jshort, jshort, jshort);

/*
 * Class:     jogl_JoglCanvas
 * Method:    color4b
 * Signature: (BBBB)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_color4b
  (JNIEnv *, jobject, jbyte, jbyte, jbyte, jbyte);

/*
 * Class:     jogl_JoglCanvas
 * Method:    color4d
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_color4d
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     jogl_JoglCanvas
 * Method:    color4f
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_color4f
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    color4i
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_color4i
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    color4s
 * Signature: (SSSS)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_color4s
  (JNIEnv *, jobject, jshort, jshort, jshort, jshort);

/*
 * Class:     jogl_JoglCanvas
 * Method:    colorMask
 * Signature: (ZZZZ)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_colorMask
  (JNIEnv *, jobject, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     jogl_JoglCanvas
 * Method:    colorMaterial
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_colorMaterial
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    copyPixels
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_copyPixels
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    cullFace
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_cullFace
  (JNIEnv *, jobject, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    deleteLists
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_deleteLists
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    depthFunc
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_depthFunc
  (JNIEnv *, jobject, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    depthMask
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_depthMask
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jogl_JoglCanvas
 * Method:    depthRange
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_depthRange
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     jogl_JoglCanvas
 * Method:    disable
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_disable
  (JNIEnv *, jobject, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    drawBuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_drawBuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    edgeFlag
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_edgeFlag
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jogl_JoglCanvas
 * Method:    enable
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_enable
  (JNIEnv *, jobject, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    end
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_end
  (JNIEnv *, jobject);

/*
 * Class:     jogl_JoglCanvas
 * Method:    endList
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_endList
  (JNIEnv *, jobject);

/*
 * Class:     jogl_JoglCanvas
 * Method:    errorString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jogl_JoglCanvas_errorString
  (JNIEnv *, jobject, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    evalCoord1d
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_evalCoord1d
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jogl_JoglCanvas
 * Method:    evalCoord1f
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_evalCoord1f
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    evalCoord2d
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_evalCoord2d
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     jogl_JoglCanvas
 * Method:    evalCoord2f
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_evalCoord2f
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    evalMesh1
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_evalMesh1
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    evalMesh2
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_evalMesh2
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    evalPoint1
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_evalPoint1
  (JNIEnv *, jobject, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    evalPoint2
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_evalPoint2
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    finish
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_finish
  (JNIEnv *, jobject);

/*
 * Class:     jogl_JoglCanvas
 * Method:    flush
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_flush
  (JNIEnv *, jobject);

/*
 * Class:     jogl_JoglCanvas
 * Method:    fogf
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_fogf
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    fogfv
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_fogfv
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    fogi
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_fogi
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    fogiv
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_fogiv
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    frontFace
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_frontFace
  (JNIEnv *, jobject, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    frustum
 * Signature: (DDDDDD)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_frustum
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     jogl_JoglCanvas
 * Method:    genLists
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jogl_JoglCanvas_genLists
  (JNIEnv *, jobject, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    genTextures
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jogl_JoglCanvas_genTextures
  (JNIEnv *, jobject, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    getString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jogl_JoglCanvas_getString
  (JNIEnv *, jobject, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    getb
 * Signature: (I[Z)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_getb
  (JNIEnv *, jobject, jint, jbooleanArray);

/*
 * Class:     jogl_JoglCanvas
 * Method:    getd
 * Signature: (I[D)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_getd
  (JNIEnv *, jobject, jint, jdoubleArray);

/*
 * Class:     jogl_JoglCanvas
 * Method:    getf
 * Signature: (I[F)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_getf
  (JNIEnv *, jobject, jint, jfloatArray);

/*
 * Class:     jogl_JoglCanvas
 * Method:    geti
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_geti
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     jogl_JoglCanvas
 * Method:    hint
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_hint
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    indexMask
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_indexMask
  (JNIEnv *, jobject, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    indexd
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_indexd
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jogl_JoglCanvas
 * Method:    indexf
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_indexf
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    indexi
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_indexi
  (JNIEnv *, jobject, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    indexs
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_indexs
  (JNIEnv *, jobject, jshort);

/*
 * Class:     jogl_JoglCanvas
 * Method:    initGL
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jogl_JoglCanvas_initGL
  (JNIEnv *, jobject);

/*
 * Class:     jogl_JoglCanvas
 * Method:    isEnabled
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jogl_JoglCanvas_isEnabled
  (JNIEnv *, jobject, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    isList
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jogl_JoglCanvas_isList
  (JNIEnv *, jobject, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    lightModelf
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_lightModelf
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    lightModelfv
 * Signature: (I[F)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_lightModelfv
  (JNIEnv *, jobject, jint, jfloatArray);

/*
 * Class:     jogl_JoglCanvas
 * Method:    lightModeli
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_lightModeli
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    lightModeliv
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_lightModeliv
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     jogl_JoglCanvas
 * Method:    lightf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_lightf
  (JNIEnv *, jobject, jint, jint, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    lightfv
 * Signature: (IIFFFF)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_lightfv
  (JNIEnv *, jobject, jint, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    lighti
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_lighti
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    lightiv
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_lightiv
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    lineStipple
 * Signature: (IS)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_lineStipple
  (JNIEnv *, jobject, jint, jshort);

/*
 * Class:     jogl_JoglCanvas
 * Method:    lineWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_lineWidth
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    loadIdentity
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_loadIdentity
  (JNIEnv *, jobject);

/*
 * Class:     jogl_JoglCanvas
 * Method:    loadMatrixd
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_loadMatrixd
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     jogl_JoglCanvas
 * Method:    loadMatrixf
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_loadMatrixf
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     jogl_JoglCanvas
 * Method:    loadName
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_loadName
  (JNIEnv *, jobject, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    logicOp
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_logicOp
  (JNIEnv *, jobject, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    lookAt
 * Signature: (DDDDDDDDD)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_lookAt
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     jogl_JoglCanvas
 * Method:    mapGrid1d
 * Signature: (IDD)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_mapGrid1d
  (JNIEnv *, jobject, jint, jdouble, jdouble);

/*
 * Class:     jogl_JoglCanvas
 * Method:    mapGrid1f
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_mapGrid1f
  (JNIEnv *, jobject, jint, jfloat, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    mapGrid2d
 * Signature: (IDDIDD)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_mapGrid2d
  (JNIEnv *, jobject, jint, jdouble, jdouble, jint, jdouble, jdouble);

/*
 * Class:     jogl_JoglCanvas
 * Method:    mapGrid2f
 * Signature: (IFFIFF)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_mapGrid2f
  (JNIEnv *, jobject, jint, jfloat, jfloat, jint, jfloat, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    materialf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_materialf
  (JNIEnv *, jobject, jint, jint, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    materialfv
 * Signature: (IIFFFF)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_materialfv
  (JNIEnv *, jobject, jint, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    materiali
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_materiali
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    materialiv
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_materialiv
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    matrixMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_matrixMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    multMatrixd
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_multMatrixd
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     jogl_JoglCanvas
 * Method:    multMatrixf
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_multMatrixf
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     jogl_JoglCanvas
 * Method:    newList
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_newList
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    normal3b
 * Signature: (BBB)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_normal3b
  (JNIEnv *, jobject, jbyte, jbyte, jbyte);

/*
 * Class:     jogl_JoglCanvas
 * Method:    normal3d
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_normal3d
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     jogl_JoglCanvas
 * Method:    normal3f
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_normal3f
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    normal3i
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_normal3i
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    normal3s
 * Signature: (SSS)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_normal3s
  (JNIEnv *, jobject, jshort, jshort, jshort);

/*
 * Class:     jogl_JoglCanvas
 * Method:    ortho
 * Signature: (DDDDDD)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_ortho
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     jogl_JoglCanvas
 * Method:    ortho2D
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_ortho2D
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     jogl_JoglCanvas
 * Method:    passThrough
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_passThrough
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    perspective
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_perspective
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     jogl_JoglCanvas
 * Method:    pickMatrix
 * Signature: (DDDD[I)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_pickMatrix
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jintArray);

/*
 * Class:     jogl_JoglCanvas
 * Method:    pixelStoref
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_pixelStoref
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    pixelStorei
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_pixelStorei
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    pointSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_pointSize
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    polygonMode
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_polygonMode
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    popAttrib
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_popAttrib
  (JNIEnv *, jobject);

/*
 * Class:     jogl_JoglCanvas
 * Method:    popMatrix
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_popMatrix
  (JNIEnv *, jobject);

/*
 * Class:     jogl_JoglCanvas
 * Method:    popName
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_popName
  (JNIEnv *, jobject);

/*
 * Class:     jogl_JoglCanvas
 * Method:    project
 * Signature: (DDD[D[D[ILjava/lang/Double;Ljava/lang/Double;Ljava/lang/Double;)I
 */
JNIEXPORT jint JNICALL Java_jogl_JoglCanvas_project
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdoubleArray, jdoubleArray, jintArray, jobject, jobject, jobject);

/*
 * Class:     jogl_JoglCanvas
 * Method:    pushAttrib
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_pushAttrib
  (JNIEnv *, jobject, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    pushMatrix
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_pushMatrix
  (JNIEnv *, jobject);

/*
 * Class:     jogl_JoglCanvas
 * Method:    pushName
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_pushName
  (JNIEnv *, jobject, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    rasterPos2d
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_rasterPos2d
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     jogl_JoglCanvas
 * Method:    rasterPos2f
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_rasterPos2f
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    rasterPos2i
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_rasterPos2i
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    rasterPos2s
 * Signature: (SS)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_rasterPos2s
  (JNIEnv *, jobject, jshort, jshort);

/*
 * Class:     jogl_JoglCanvas
 * Method:    rasterPos3d
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_rasterPos3d
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     jogl_JoglCanvas
 * Method:    rasterPos3f
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_rasterPos3f
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    rasterPos3i
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_rasterPos3i
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    rasterPos3s
 * Signature: (SSS)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_rasterPos3s
  (JNIEnv *, jobject, jshort, jshort, jshort);

/*
 * Class:     jogl_JoglCanvas
 * Method:    readBuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_readBuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    rectd
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_rectd
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     jogl_JoglCanvas
 * Method:    rectf
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_rectf
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    recti
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_recti
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    renderMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_renderMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    rotated
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_rotated
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     jogl_JoglCanvas
 * Method:    rotatef
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_rotatef
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    scaleImage
 * Signature: (IIIILjava/lang/Object;IIILjava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_jogl_JoglCanvas_scaleImage
  (JNIEnv *, jobject, jint, jint, jint, jint, jobject, jint, jint, jint, jobject);

/*
 * Class:     jogl_JoglCanvas
 * Method:    scaled
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_scaled
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     jogl_JoglCanvas
 * Method:    scalef
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_scalef
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    scissor
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_scissor
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    shadeModel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_shadeModel
  (JNIEnv *, jobject, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    stencilFunc
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_stencilFunc
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    stencilMask
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_stencilMask
  (JNIEnv *, jobject, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    stencilOp
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_stencilOp
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    swap
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_swap
  (JNIEnv *, jobject);

/*
 * Class:     jogl_JoglCanvas
 * Method:    texCoord1d
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_texCoord1d
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jogl_JoglCanvas
 * Method:    texCoord1f
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_texCoord1f
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    texCoord1i
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_texCoord1i
  (JNIEnv *, jobject, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    texCoord1s
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_texCoord1s
  (JNIEnv *, jobject, jshort);

/*
 * Class:     jogl_JoglCanvas
 * Method:    texCoord2d
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_texCoord2d
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     jogl_JoglCanvas
 * Method:    texCoord2f
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_texCoord2f
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    texCoord2i
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_texCoord2i
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    texCoord2s
 * Signature: (SS)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_texCoord2s
  (JNIEnv *, jobject, jshort, jshort);

/*
 * Class:     jogl_JoglCanvas
 * Method:    texCoord3d
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_texCoord3d
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     jogl_JoglCanvas
 * Method:    texCoord3f
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_texCoord3f
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    texCoord3i
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_texCoord3i
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    texCoord3s
 * Signature: (SSS)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_texCoord3s
  (JNIEnv *, jobject, jshort, jshort, jshort);

/*
 * Class:     jogl_JoglCanvas
 * Method:    texCoord4d
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_texCoord4d
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     jogl_JoglCanvas
 * Method:    texCoord4f
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_texCoord4f
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    texCoord4i
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_texCoord4i
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    texCoord4s
 * Signature: (SSSS)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_texCoord4s
  (JNIEnv *, jobject, jshort, jshort, jshort, jshort);

/*
 * Class:     jogl_JoglCanvas
 * Method:    texEnvf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_texEnvf
  (JNIEnv *, jobject, jint, jint, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    texEnvi
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_texEnvi
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    texGend
 * Signature: (IID)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_texGend
  (JNIEnv *, jobject, jint, jint, jdouble);

/*
 * Class:     jogl_JoglCanvas
 * Method:    texGenf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_texGenf
  (JNIEnv *, jobject, jint, jint, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    texGeni
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_texGeni
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    texImage1D
 * Signature: (IIIIIII[B)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_texImage1D
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jbyteArray);

/*
 * Class:     jogl_JoglCanvas
 * Method:    texImage2Db
 * Signature: (IIIIIIII[[[B)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_texImage2Db
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint, jobjectArray);

/*
 * Class:     jogl_JoglCanvas
 * Method:    texImage2Di
 * Signature: (IIIIIIII[I)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_texImage2Di
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint, jintArray);

/*
 * Class:     jogl_JoglCanvas
 * Method:    texParameterf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_texParameterf
  (JNIEnv *, jobject, jint, jint, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    texParameteri
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_texParameteri
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    translated
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_translated
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     jogl_JoglCanvas
 * Method:    translatef
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_translatef
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    unProject
 * Signature: (DDD[D[D[ILjava/lang/Double;Ljava/lang/Double;Ljava/lang/Double;)I
 */
JNIEXPORT jint JNICALL Java_jogl_JoglCanvas_unProject
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdoubleArray, jdoubleArray, jintArray, jobject, jobject, jobject);

/*
 * Class:     jogl_JoglCanvas
 * Method:    use
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jogl_JoglCanvas_use
  (JNIEnv *, jobject);

/*
 * Class:     jogl_JoglCanvas
 * Method:    vertex2d
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_vertex2d
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     jogl_JoglCanvas
 * Method:    vertex2f
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_vertex2f
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    vertex2i
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_vertex2i
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    vertex2s
 * Signature: (SS)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_vertex2s
  (JNIEnv *, jobject, jshort, jshort);

/*
 * Class:     jogl_JoglCanvas
 * Method:    vertex3d
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_vertex3d
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     jogl_JoglCanvas
 * Method:    vertex3f
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_vertex3f
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    vertex3i
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_vertex3i
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    vertex3s
 * Signature: (SSS)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_vertex3s
  (JNIEnv *, jobject, jshort, jshort, jshort);

/*
 * Class:     jogl_JoglCanvas
 * Method:    vertex4d
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_vertex4d
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     jogl_JoglCanvas
 * Method:    vertex4f
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_vertex4f
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     jogl_JoglCanvas
 * Method:    vertex4i
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_vertex4i
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     jogl_JoglCanvas
 * Method:    vertex4s
 * Signature: (SSSS)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_vertex4s
  (JNIEnv *, jobject, jshort, jshort, jshort, jshort);

/*
 * Class:     jogl_JoglCanvas
 * Method:    viewport
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_jogl_JoglCanvas_viewport
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
