/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jogl_glu_Quadric */

#ifndef _Included_jogl_glu_Quadric
#define _Included_jogl_glu_Quadric
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jogl_glu_Quadric
 * Method:    newQuadric
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jogl_glu_Quadric_newQuadric
  (JNIEnv *, jobject);

/*
 * Class:     jogl_glu_Quadric
 * Method:    deleteQuadric
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jogl_glu_Quadric_deleteQuadric
  (JNIEnv *, jobject);

/*
 * Class:     jogl_glu_Quadric
 * Method:    quadricDrawStyle
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jogl_glu_Quadric_quadricDrawStyle
  (JNIEnv *, jobject, jint);

/*
 * Class:     jogl_glu_Quadric
 * Method:    quadricOrientation
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jogl_glu_Quadric_quadricOrientation
  (JNIEnv *, jobject, jint);

/*
 * Class:     jogl_glu_Quadric
 * Method:    quadricNormals
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jogl_glu_Quadric_quadricNormals
  (JNIEnv *, jobject, jint);

/*
 * Class:     jogl_glu_Quadric
 * Method:    quadricTexture
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jogl_glu_Quadric_quadricTexture
  (JNIEnv *, jobject, jint);

/*
 * Class:     jogl_glu_Quadric
 * Method:    cylinder
 * Signature: (DDDII)V
 */
JNIEXPORT void JNICALL Java_jogl_glu_Quadric_cylinder
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     jogl_glu_Quadric
 * Method:    disk
 * Signature: (DDII)V
 */
JNIEXPORT void JNICALL Java_jogl_glu_Quadric_disk
  (JNIEnv *, jobject, jdouble, jdouble, jint, jint);

/*
 * Class:     jogl_glu_Quadric
 * Method:    sphere
 * Signature: (DII)V
 */
JNIEXPORT void JNICALL Java_jogl_glu_Quadric_sphere
  (JNIEnv *, jobject, jdouble, jint, jint);

/*
 * Class:     jogl_glu_Quadric
 * Method:    partialDisk
 * Signature: (DDIIDD)V
 */
JNIEXPORT void JNICALL Java_jogl_glu_Quadric_partialDisk
  (JNIEnv *, jobject, jdouble, jdouble, jint, jint, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
