/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jogl_glu_Tesselator */

#ifndef _Included_jogl_glu_Tesselator
#define _Included_jogl_glu_Tesselator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jogl_glu_Tesselator
 * Method:    newTess
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jogl_glu_Tesselator_newTess
  (JNIEnv *, jobject);

/*
 * Class:     jogl_glu_Tesselator
 * Method:    deleteTess
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jogl_glu_Tesselator_deleteTess
  (JNIEnv *, jobject);

/*
 * Class:     jogl_glu_Tesselator
 * Method:    beginPolygon
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jogl_glu_Tesselator_beginPolygon
  (JNIEnv *, jobject);

/*
 * Class:     jogl_glu_Tesselator
 * Method:    endPolygon
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jogl_glu_Tesselator_endPolygon
  (JNIEnv *, jobject);

/*
 * Class:     jogl_glu_Tesselator
 * Method:    nextContour
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jogl_glu_Tesselator_nextContour
  (JNIEnv *, jobject, jint);

/*
 * Class:     jogl_glu_Tesselator
 * Method:    tessVertex
 * Signature: ([DLjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_jogl_glu_Tesselator_tessVertex
  (JNIEnv *, jobject, jdoubleArray, jobject);

/*
 * Class:     jogl_glu_Tesselator
 * Method:    tessCallback
 * Signature: (ILjava/lang/Object;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jogl_glu_Tesselator_tessCallback
  (JNIEnv *, jobject, jint, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
