# Makefile for SGIs
# Wm. Randolph Franklin
# Time-stamp: </afs/rpi.edu/home/56/frankwr/public_html/ECSE-4750/h02/Makefile, Wed, 13 Jan 1999, 02:09:53 IST, wrf@speed.ecse.rpi.edu>



LDFLAGS= -lXm -lXmu -lXt -lX11 
